# Copyright (C) 2026 Neil Rackett
# SPDX-License-Identifier: GPL-3.0-or-later
#
# tools/gen_bluenoise.py
#
# Generate a tileable blue-noise threshold matrix (Ulichney's
# void-and-cluster method) and emit it as rp/src/include/bluenoise.h
# for MD/DOOM's blue-noise dither mode.
#
# The matrix is quantized to 16 levels (0..15) so it drops straight
# into the same 16-entry pre-shifted dither LUTs the 4x4 Bayer path
# uses -- the ONLY thing that changes between Bayer and blue noise is
# which threshold level each screen cell gets, so it's an honest A/B
# of the dither *pattern* (regular crosshatch vs isotropic grain) at
# identical cost. Being `const`, the matrix lives in flash: no RAM.
#
# Deterministic (fixed seed) so rebuilds are reproducible. Run:
#   python3 tools/gen_bluenoise.py
#
# Requires numpy + scipy (host-only; not part of the firmware build).

import numpy as np
from scipy.ndimage import gaussian_filter

N = 32                       # 32x32 tile: tiling invisible at 320x200
M = N * N
SIGMA = 1.9                  # Ulichney's filter width (~1.5-2.0)
LEVELS = 16                  # quantize ranks -> 0..15 (matches the LUTs)
SEED = 20260711
OUT = "rp/src/include/bluenoise.h"


def energy(binary):
    """Toroidal Gaussian filter -- high where minority pixels cluster."""
    return gaussian_filter(binary.astype(np.float64), SIGMA, mode="wrap")


def tightest_cluster(binary):  # 1-pixel in the densest clump
    f = np.where(binary == 1, energy(binary), -np.inf)
    return np.unravel_index(np.argmax(f), f.shape)


def largest_void(binary):      # 0-pixel in the emptiest region
    f = np.where(binary == 0, energy(binary), np.inf)
    return np.unravel_index(np.argmin(f), f.shape)


def main():
    rng = np.random.default_rng(SEED)

    # Initial minority pattern (~10% ones), then relax to homogeneous.
    ones = M // 10
    binary = np.zeros((N, N), dtype=np.uint8)
    flat = rng.choice(M, size=ones, replace=False)
    binary.flat[flat] = 1
    while True:
        c = tightest_cluster(binary)
        binary[c] = 0
        v = largest_void(binary)
        binary[v] = 1
        if c == v:
            break

    prototype = binary.copy()
    rank = np.zeros((N, N), dtype=np.int64)

    # Phase 1: peel clusters off the prototype -> ranks ones-1 .. 0.
    binary = prototype.copy()
    for r in range(ones - 1, -1, -1):
        c = tightest_cluster(binary)
        binary[c] = 0
        rank[c] = r

    # Phase 2: fill voids -> ranks ones .. M/2-1.
    binary = prototype.copy()
    for r in range(ones, (M + 1) // 2):
        v = largest_void(binary)
        binary[v] = 1
        rank[v] = r

    # Phase 3: minority is now the 0s -> ranks M/2 .. M-1.
    for r in range((M + 1) // 2, M):
        f = np.where(binary == 0, energy(binary), np.inf)
        loc = np.unravel_index(np.argmin(f), f.shape)
        binary[loc] = 1
        rank[loc] = r

    # Ranks 0..M-1 -> threshold levels 0..LEVELS-1.
    levels = (rank * LEVELS) // M
    assert levels.min() == 0 and levels.max() == LEVELS - 1

    with open(OUT, "w") as f:
        f.write("/*\n * Copyright (C) 2026 Neil Rackett\n"
                " * SPDX-License-Identifier: GPL-3.0-or-later\n */\n\n")
        f.write("/* Generated by tools/gen_bluenoise.py -- DO NOT EDIT.\n"
                " * %dx%d void-and-cluster blue-noise threshold matrix,\n"
                " * quantized to %d levels. Indexed bluenoise[(y & %d) * %d\n"
                " * + (x & %d)]; the value is the dither LUT level (0..%d).\n"
                " * `const` -> lives in flash, costs no RAM. */\n\n"
                % (N, N, LEVELS, N - 1, N, N - 1, LEVELS - 1))
        f.write("#ifndef BLUENOISE_H_INCLUDED\n#define BLUENOISE_H_INCLUDED\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define BLUENOISE_N %d\n\n" % N)
        f.write("static const uint8_t bluenoise[BLUENOISE_N * BLUENOISE_N] = {\n")
        flat = levels.flatten()
        for row in range(0, M, 16):
            f.write("    " + ", ".join("%2d" % v for v in flat[row:row + 16]) + ",\n")
        f.write("};\n\n#endif /* BLUENOISE_H_INCLUDED */\n")

    print("wrote %s (%dx%d, %d levels, sigma=%.1f)" % (OUT, N, N, LEVELS, SIGMA))


if __name__ == "__main__":
    main()
