#!/usr/bin/env python3
#
# Copyright (C) 2026 Neil Rackett
# SPDX-License-Identifier: GPL-3.0-or-later
#
"""Convert a 320x200 black-and-white PNG into a 1-bit-per-pixel C array.

    png_to_mono.py desc/bg-mono.png rp/src/include/bg_mono.h bg_mono

The output is 8,000 bytes, one bit per pixel, MSB first, rows top to
bottom, 1 = white. md_main.c expands it into the framebuffer as the
backdrop for the firmware's own screens (loading, missing packs).
"""
import sys
from PIL import Image

src, dst, name = sys.argv[1:4]
im = Image.open(src).convert('1')
w, h = im.size
if (w, h) != (320, 200):
    sys.exit(f'{src} is {w}x{h}, need 320x200')
px = im.load()
data = bytearray()
for y in range(h):
    for x in range(0, w, 8):
        b = 0
        for i in range(8):
            if px[x + i, y]:
                b |= 0x80 >> i
        data.append(b)
with open(dst, 'w') as f:
    f.write('/* Generated by tools/png_to_mono.py from %s -- do not edit. */\n' % src)
    f.write('#include <stdint.h>\n')
    f.write('const uint8_t %s[%d] = {\n' % (name, len(data)))
    for i in range(0, len(data), 20):
        f.write('    ' + ', '.join('0x%02X' % v for v in data[i:i + 20]) + ',\n')
    f.write('};\n')
print(f'{dst}: {len(data)} bytes')
